apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: npqud7u7y-python-gitops
  description: This is GitOps manifest for npqud7u7y-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=npqud7u7y-python
    backstage.io/kubernetes-id: npqud7u7y-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: npqud7u7y-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:npqud7u7y-python
